general.import = [
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/..config/alacritty/black-metal-gorgoroth.toml"
]

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/zsh"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.9

#[cursor]
#smooth_motion = true
#smooth_motion_factor = 0.9
#smooth_motion_spring = 0.5
#smooth_motion_max_stretch_x = 3.0
#smooth_motion_max_stretch_y = 3.0
#block_replace_shape = "underline"


