"$schema" = 'https://starship.rs/config-schema.json'
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#c1c1c1" # Pinkish grey

[character]
# Explicitly control the position with no newline
format = "$symbol"
success_symbol = "[λ ](#888888)" # muted gray with space after lambda
error_symbol = "[λ ](#9b8d7f)"   # warm gray for errors with space after lambda
vimcmd_symbol = "[λ ](#666666)"  # darker gray for vim with space after lambda

[git_branch]
format = "[$branch]($style)"
style = "#9A8481" # Pinkish grey shade

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "#5f8787" # signature teal again for status
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#666666" # darker gray

[cmd_duration]
format = "[$duration]($style) "
style = "#8c7f70" # muted brown

[python]
format = "[$virtualenv]($style) "
style = "#444444" # subtle dark gray
