"$schema" = 'https://starship.rs/config-schema.json'
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#8ba4b0" # Kanso soft blue

[character]
# Explicitly control the position with no newline
format = "$symbol"
success_symbol = "[λ ](#888888)" # muted gray with space after lambda
error_symbol = "[λ ](#c4746e)"   # Kanso coral for errors with space after lambda
vimcmd_symbol = "[λ ](#8ba4b0)"  # Kanso steel blue for vim with space after lambda

[git_branch]
format = "[$branch]($style)"
style = "#8a9a7b" # Kanso sage

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)( $ahead_behind)]($style)[( $stashed)](#e6c384)"
style = "#5f8787" # signature teal again for status
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#666666" # darker gray

[cmd_duration]
format = " [$duration]($style) "
style = "#907aa9" # iris

[python]
format = "[$virtualenv]($style) "
style = "#c4b28a" # Kanso warm tan

