theme = "catppuccin-mocha"
diff_view = "side-by-side"
ignore_whitespace = false
appearance = "dark"
mouse = true 
leader = ";"
review_watch_interval_ms = 1000 

[[comment_types]]
id = "issue"
color = "red"
defintion = "must fix prior to merge"
